### ISSUE TITLE
Can't make photorealistic images

### ISSUE THREAD

**Issue by ckao10301** [meap158/ComfyUI-Prompt-Expansion#2]
It's really good at art, but can you add an option for photorealistic style prompt? It keep adding "digital art, concept art", to my prompt.

**Comment by meap158** [comment]
Well, I'd suggest you use some text manipulation nodes to remove those unwanted keywords.

**Comment by mickyboys** [comment]
:-) That can't be your answer... I mean, GPT2 should introduce simplification in prompt creation and now that we get bad or unwanted GPT2 results, you ask to reverse engineer the bad results with counter argues in the original prompts. Look, I know you haven't done it, it comes to some extent from Fooocus, but the difference there is that it works, you don't get unwanted prompts or 3 and more artists names that screw up your results. I do seriously appreciate your efforts in helping the community to use these in theory great functionalities in ComfyUI - really … it just does not work, unfortunately. Even if I say realistic, etc. it adds digital art, or painting or oil painting and on top several artists names that it should copy the style from… Impossible to get great results.
